// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-mBwacdNynasK3VsgQtIRAkbu3gzMco',
    appId: '1:165834640851:web:ae6092a3564b77f822b326',
    messagingSenderId: '165834640851',
    projectId: 'chat-app-69ceb',
    authDomain: 'chat-app-69ceb.firebaseapp.com',
    storageBucket: 'chat-app-69ceb.firebasestorage.app',
    measurementId: 'G-M0FJ48CMJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkt7CpzNUNurBz-N0SJIDT5BTOfykutjw',
    appId: '1:165834640851:android:2893a764a9ca87e722b326',
    messagingSenderId: '165834640851',
    projectId: 'chat-app-69ceb',
    storageBucket: 'chat-app-69ceb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoieLKOBI8WHpbmsleYn3fKZ0WVR6mKso',
    appId: '1:165834640851:ios:bd26ac7141367c1c22b326',
    messagingSenderId: '165834640851',
    projectId: 'chat-app-69ceb',
    storageBucket: 'chat-app-69ceb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoieLKOBI8WHpbmsleYn3fKZ0WVR6mKso',
    appId: '1:165834640851:ios:bd26ac7141367c1c22b326',
    messagingSenderId: '165834640851',
    projectId: 'chat-app-69ceb',
    storageBucket: 'chat-app-69ceb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH-mBwacdNynasK3VsgQtIRAkbu3gzMco',
    appId: '1:165834640851:web:80cde977cb4c0f8f22b326',
    messagingSenderId: '165834640851',
    projectId: 'chat-app-69ceb',
    authDomain: 'chat-app-69ceb.firebaseapp.com',
    storageBucket: 'chat-app-69ceb.firebasestorage.app',
    measurementId: 'G-W38ZN6CJYJ',
  );

}